### ISSUE TITLE
Bug: overlay does not exist

### ISSUE THREAD

**Issue by mattybojo** [mattybojo/renoir-old#31]
Error seems to be coming from @angular/fire.  Only way to reproduce seems to be clicking on various tabs and waiting for the error to show up in console.  Need to do more research.

Stack trace:

ERROR Error: Uncaught (in promise): overlay does not exist
    at resolvePromise (zone.js:1262:35)
    at zone.js:1169:21
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _throw (asyncToGenerator.js:29:1)
    at _ZoneDelegate.invoke (zone.js:409:30)
    at Object.onInvoke (core.mjs:26514:33)
    at _ZoneDelegate.invoke (zone.js:408:56)
    at Zone.run (zone.js:169:47)
    at zone.js:1326:38

**Comment by mattybojo** [comment]
Possible issue: Check `AppService` code.  Could be that multiple loaders are being started in the same timeframe. If the first one closes the loading modal, it could be that the second one is trying to close a modal that no longer exists (hence overlay does not exist).
